apiVersion: v1
kind: ConfigMap
metadata:
  name: catalog-db-config
  namespace: retail-app
data: 
  DB_HOST: "project-bedrock-mysql.ck7w6w04w7k0.us-east-1.rds.amazonaws.com"
  DB_PORT: "3306"
  DB_NAME: "catalog"
