apiVersion: v1
kind: Secret
metadata:
  name: retail-db-secrets
  namespace: retail-app
type: Opaque
stringData:
  MYSQL_USERNAME: "catalogadmin"
  MYSQL_PASSWORD: "KUTpYG9MShbV1z6DZXyeQj9x"
  POSTGRES_USERNAME: "ordersadmin" 
  POSTGRES_PASSWORD: "5XV3vVosbj7GPj0EBbC8U6Lg"
