apiVersion: v1
kind: ConfigMap
metadata:
  name: ui
  namespace: retail-app
data:
  ENDPOINTS_CATALOG: "http://catalog:8080"
  ENDPOINTS_CARTS: "http://cart:8080"
  ENDPOINTS_CHECKOUT: "http://checkout:8080"
  ENDPOINTS_ORDERS: "http://orders:8080"
  ENDPOINTS_ASSETS: "http://assets:8080"
